USE [master]
GO

/****** Object:  Database [Clinic System]    Script Date: 1/3/2024 10:40:17 AM ******/
CREATE DATABASE [Clinic System]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Clinic System', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Clinic System.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Clinic System_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Clinic System_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Clinic System].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Clinic System] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Clinic System] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Clinic System] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Clinic System] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Clinic System] SET ARITHABORT OFF 
GO

ALTER DATABASE [Clinic System] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Clinic System] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Clinic System] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Clinic System] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Clinic System] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Clinic System] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Clinic System] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Clinic System] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Clinic System] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Clinic System] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Clinic System] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Clinic System] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Clinic System] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Clinic System] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Clinic System] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Clinic System] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Clinic System] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Clinic System] SET RECOVERY FULL 
GO

ALTER DATABASE [Clinic System] SET  MULTI_USER 
GO

ALTER DATABASE [Clinic System] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Clinic System] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Clinic System] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Clinic System] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Clinic System] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Clinic System] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Clinic System] SET QUERY_STORE = ON
GO

ALTER DATABASE [Clinic System] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Clinic System] SET  READ_WRITE 
GO


